# Generated by Django 4.2.19 on 2025-03-02 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Is in the process"),
                            ("PAID", "Successfully paid"),
                            ("FAILED", "Payment failed"),
                            ("CANCELED", "Payment canceled"),
                            ("REFUNDED", "Payment refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "Common payment"), ("FINE", "Penalty")],
                        default="PAYMENT",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("borrow_date", models.DateField()),
                (
                    "payment_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("USD", "US Dollar"), ("EUR", "Euro")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status"], name="payments_st_status_6e7ca7_idx"
                    ),
                    models.Index(
                        fields=["borrowing"], name="payments_st_borrowi_edd98e_idx"
                    ),
                ],
            },
        ),
    ]
