# Generated by Django 4.2.19 on 2025-03-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypalpayment",
            name="currency",
            field=models.CharField(
                blank=True, choices=[("USD", "US Dollar")], default="USD", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="stripepayment",
            name="currency",
            field=models.CharField(
                blank=True, choices=[("USD", "US Dollar")], default="USD", max_length=3
            ),
        ),
    ]
