# Generated by Django 4.2.19 on 2025-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paypalpayment_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypalpayment",
            name="approval_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="stripepayment",
            name="session_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
